# -*- coding: utf-8 -*-
"""LoveCalculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kl0O56qaqbbgsvpTLKhbLPI6YukPH2Tk
"""

#Building a love calculator

boy_name = input("Enter 'HIS' first name: ")
girl_name = input("Enter 'HER' first name: ")
couple_name = boy_name.lower() + girl_name.lower()

t = couple_name.count('t')
r = couple_name.count('r')
u = couple_name.count('u')
e = couple_name.count('e')
l = couple_name.count('l')
o = couple_name.count('o')
v = couple_name.count('v')
e = couple_name.count('e')

love_count = t + r + u + e + l + o + v + e

print(f"{boy_name}'s and {girl_name}'s love count is {love_count}/10")

